### PR TITLE
Fix/104 fix explore screen UI movies section

### LINKED ISSUE #104: Fix Explore Screen Ui (Movies Section)

### PR DESCRIPTION
**Pull request by hazemka**

### CODE REVIEW

**Review by nourelhodaahmed — APPROVED** [review]

File: presentation/src/main/java/com/moscow/cineverse/screen/explore/MoviePosterCard.kt [hunk 1]
```diff
@@ -1,4 +1,4 @@
-package com.moscow.cineverse.presentation.component
```
Comment (khaledeid1k) [inline presentation/src/main/java/com/moscow/cineverse/screen/explore/MoviePosterCard.kt:1]: Why move it to the explore package when we need out of the explored screen

Comment (hazemka) [reply presentation/src/main/java/com/moscow/cineverse/screen/explore/MoviePosterCard.kt:1]: Package directive does not match the file location 

image

**Review by khaledeid1k — APPROVED** [review]
